cluster.name: CSP-cluster
network.host: 0.0.0.0

# minimum_master_nodes need to be explicitly set when bound on a public IP
# set to 1 to allow single node clusters
# Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1
xpack.security.enabled: false
xpack.watcher.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
path.data: /usr/share/elasticsearch/data
path.repo: ["/backup"]
node.max_local_storage_nodes: 2